title: "Álvaro Peláez Piñera"
description: ""
baseurl: ""
url: "https://alvaro-pelaez.github.io/"

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

author:
  name: Álvaro Peláez Piñera
  email: alvaropelaez.es@gmail.com
photo: assets/images/profile.jpg

#joblines:
#  - Babel Group
#  - Software Engineer - Fullstack - Competent
#adresss: Oviedo, Asturias

# profile links
profile:
  facebook: https://www.facebook.com/alvaro.pelaez
  bluesky: https://bsky.app/profile/fichi.bsky.social
  instagram: https://www.instagram.com/alvaro___85
  linkedin: https://www.linkedin.com/in/alvaropelaezpinera
  github: https://github.com/alvaro-pelaez
  
